host = "localhost"
port = 8080
execution_properties = {}
append_to_existing_execution = False
existing_execution_id = -1
execution_description = "Default"
num_of_suites_to_ignore = -1
planned_tests = 100
force_new_execution = False
use_shared_execution = False
output_folder = "report"
reporters: str = "difido.reporters.LocalReporter,difido.reporters.ConsoleReporter"
